name: absensi_mattaher
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  path: ^1.8.3
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  nb_utils: ^6.1.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/absensi/
    - assets/images/profil/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logors.png"
  min_sdk_android: 21
