name: Build and Release Flutter App

on:
  push:
    branches:
<<<<<<< HEAD
      - main
=======
      - master 

name: Build My Apps
>>>>>>> 03c4d25301814baa8193cddd6faa8ed0a8b331d4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout Repository
        uses: actions/checkout@v2
=======
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11" 
>>>>>>> 03c4d25301814baa8193cddd6faa8ed0a8b331d4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Flutter App
        run: flutter build apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: Automated release generated by GitHub Actions.

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
